name: E-Commerce Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SAUCE_USERNAME : oauth-kannanvishnupriya840-4f22f
      SAUCE_ACCESS_KEY : 5e679d10-5244-4950-ab4a-e7119f51adf6
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run Tests
        run: mvn clean test
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports/